ALTER TABLE file_upload
ADD COLUMN IF NOT EXISTS ispublished BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE file_upload
ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE file_upload
ADD COLUMN IF NOT EXISTS backtocreator BOOLEAN NOT NULL DEFAULT FALSE;
